### ISSUE TITLE
Check for endswith '.gz' instead of 'eq_classes.txt.gz'

### ISSUE THREAD

**Issue by theJasonFan** [COMBINE-lab/seine-rs#2]
https://github.com/COMBINE-lab/seine-rs/blob/5c9f100f14ab9e5877fc0f06cc41464ea7d6373d/src/salmon.rs#L204

We'd just like to name equivalence class files with different names.

**Comment by evanbiederstedt** [comment]
Hi @theJasonFan 

Sorry for the random comment on an issue which you wrote during development. I was looking at this repo for a project of mine; I normally check out the existing issues to get a sense of the quality of code. 

https://github.com/COMBINE-lab/seine-rs/blob/5c9f100f14ab9e5877fc0f06cc41464ea7d6373d/src/salmon.rs#L204-L208

It looks like the correct fix here is:
(1) Check for files ending in `*.gz`, not `*.eq_classes.txt.gz`
(2) Check that the "equivalence class file" is indeed in the correct format. 
https://docs.rs/flate2/0.2.20/flate2/read/struct.GzDecoder.html will handle the errors if there are issues with the *gz compression/etc. 

Am I understanding this correctly? I'd probably be able to make a PR if so.

Thanks, Evan

**Comment by theJasonFan** [comment]
@evanbiederstedt I'll take a look! Thanks for the comment :). At this point, seine is still quite rough around the edges and has just enough functionality to support our own internal projects.

lmk if there are other issues you run into, either here or reach out via my UMD email.

**Comment by theJasonFan** [comment]
Indeed, sometimes one may want to only parse equivalence class (EC) file and rename them to something other than "eq_classes.txt.gz". 

@evanbiederstedt, verifying the EC file format would be a larger feature request :). However, it is very very unlikely for salmon to produce an incorrect EC encoding.

**Comment by evanbiederstedt** [comment]
> However, it is very very unlikely for salmon to produce an incorrect EC encoding.

Fair enough. I suppose there are users would may willfully use incorrect inputs, but that's a separate issue. 

Thanks for help!
